- name: This play will install, configure and deploy custom web page into nginx web server
  hosts: ubuntu
  become: yes
  vars:
    - tektutor_greeting_msg: DevOps!
    - tektutor_provisioner_tool: VMWare Workstation
    - tektutor_conf_mgr_tool: Ansible
  tasks:
     - name: Install nginx web server in Ubuntu
       apt: name=nginx state=latest update_cache=yes

     - name: Configure nginx web root folder in Ubuntu
       copy: src=default dest=/etc/nginx/sites-available/default

     - name: Create the custom web root folder in Ubuntu
       file: path=/var/html state=directory mode=0777

     - name: Restart nginx web server in Ubuntu
       service: name=nginx state=restarted

     - name: Deploy custom web page into nginx web server in Ubuntu
       template: src=index.html.j2 dest=/var/html/index.html mode=0777